version: '3.8'

services:
  app:
    container_name: rateLimiter
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - SERVER_PORT=8080
    depends_on:
      - redis
    networks:
      - rateLimiter_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - rateLimiter_network
    volumes:
      - redis_data:/data

networks:
  rateLimiter_network:
    driver: bridge

volumes:
  redis_data: